//lib/auth/password.ts
import bcrypt from "bcryptjs"

const SALT_ROUNDS = 10

export async function hashPassword(password: string) {
  return bcrypt.hash(password, SALT_ROUNDS)
}

export async function comparePassword(
  password: string,
  hash: string
) {
  return bcrypt.compare(password, hash)
  // bcryptjs doesn't natively support $2b$ hashes (which are generated by the native bcrypt library).
  // Replacing the $2b$ prefix with $2a$ fixes this compatibility issue.
  // const compatibleHash = hash.replace(/^\$2b\$/, "$2a$")
  // return bcrypt.compare(password, compatibleHash) 
}